# Generated by Django 3.0.8 on 2021-03-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210319_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd',
        ),
    ]
